### ISSUE TITLE
"module compiled against API version 0xe but this version of numpy is 0xd"

### ISSUE THREAD

**Issue by rainwoodman** [conda-forge/pyerfa-feedstock#18]
- [X] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:  module compiled against API version 0xe but this version of numpy is 0xd

The full log is at:

https://pipelines.actions.githubusercontent.com/4WG3RDC5LrvSQSfVuzaeJ6lLFmXDn3iE4xIDQGf4ZMGoiw0ciN/_apis/pipelines/1/runs/353/signedlogcontent/3?urlExpires=2021-06-01T01%3A26%3A49.3916756Z&urlSigningMethod=HMACV1&urlSignature=GKjPRIscFdqMrNb5DG83p7Siwo2LTAS%2FCmjMn8ZP%2FRE%3D

I think the pyerfa-2.0.0 package is likely compiled with numpy 1.20 API which means it is not backward compatible with numpy 1.18. This is probably unintended. There is a way to pin numpy to an older version during package compilation. I suspect 1.16 API is still the main stream and recommend pin to 1.16 or earlier if possible.

If a 1.20 API is really needed, I suggest declare a requirement of numpy >= 1.20 in requirements.

Thanks!

**Comment by rainwoodman** [comment]
@AnjuSThomas-anaconda; not sure if this is the right place for the issue. The broken 2.0.0 package is actually from the default channel, and I noticed the anaconda recipe and the conda-forge recipe have diverged. But here is no issue report on the default channel.

**Comment by rainwoodman** [comment]
Ping @mhvk the owner of liberfa for the awareness.  The problem may eventually spread to other users especially if they cannot freely upgrade to numpy-1.20.

**Comment by maxnoe** [comment]
I think the problem is this line here: https://github.com/conda-forge/pyerfa-feedstock/blob/ea9e07c3c6cd4a1595746413364367be73aecd94/recipe/meta.yaml#L33

Which might override the previous line of `pin_compatible`

**Comment by maxnoe** [comment]
I am experiencing the same issue with the conda-forge package version of 1.7.3

**Comment by mhvk** [comment]
I don't know enough about conda to be much help here, but will note for completeness that `pyerfa` formally requires `numpy>=1.17` - though 1.16 should really still be OK (we just followed astropy and bumped...)

**Comment by maxnoe** [comment]
ok. The main problem here seems to be that osx arm64 only has >= 1.18. Will bump to 1.17 for the rest and see how I can fix the other builds.

**Comment by rainwoodman** [comment]
Thanks for the fix. 

I checked and pyerfa is still broken on the anaconda default channel.

https://pipelines.actions.githubusercontent.com/4WG3RDC5LrvSQSfVuzaeJ6lLFmXDn3iE4xIDQGf4ZMGoiw0ciN/_apis/pipelines/1/runs/448/signedlogcontent/3?urlExpires=2021-06-13T14%3A56%3A49.3991632Z&urlSigningMethod=HMACV1&urlSignature=N8TQW%2BpGY4EVaqs9V0E7UVAYj3kUfnjWRvS41eb0Eec%3D

and filed as https://github.com/AnacondaRecipes/pyerfa-feedstock/issues/1

Could someone (ping the default channel developer: @AnjuSThomas-anaconda) pick up this and rebuild there?
